swagger: '2.0'
info:
  description: Online Note
  version: 1.0.0
  title: Notee
  # put the contact info for your development or API team
  contact:
    email: yudhaseptiandry@gmail.com

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

# tags are used for organizing operations
tags:
- name: Auth
  description: Authentication Api
- name: Categories
  description: Category Note
- name: Note
  description: Note

paths:
  /login:
    post:
      tags:
      - Auth
      summary: login users
      description: |
        Passing Username And Password to get Token JWT
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: Login User
        description: Login User
        schema:
          $ref: '#/definitions/Login'
      responses:
        200:
          description: Response Auth Login
          schema:
            type: object
            properties:
              status_code:
                type: integer
                example: 200
              message:
                type: string
                example: 'OK'
              data:
                $ref: '#/definitions/JWT'
        400:
          description: invalid input, object invalid
  /register:
    post:
      tags:
      - Auth
      summary: Register User
      description: |
        send some data register
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: Register User
        description: Register User
        schema:
          type: object
          required:
          - name
          - email
          - password
          properties:
            name:
              type: string
              example: Yudha
            email:
              type: string
              format: email
              example: yudha.pradana@amartha.com
            password:
              type: string
              example: k!UUdja21Sxh
      responses:
        200:
          description: Response User Register
          schema:
            type: object
            properties:
              status_code:
                type: integer
                example: 200
              message:
                type: string
                example: 'OK'
              data:
                $ref: '#/definitions/Register'
        400:
          description: Bad Request
  /categories:
    get:
      security:
        - bearerAuth: []
      tags:
      - Categories
      summary: Get List Data Kategori Note
      description: |
        get some data category
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        200:
          description: Response Get Category
          schema:
            type: object
            properties:
              status_code:
                type: integer
                example: 200
              message:
                type: string
                example: 'OK'
              data:
                type : array
                $ref: '#/definitions/Categories'
        400:
          description: Bad Request
    post:
      security:
          - bearerAuth: []
      tags:
      - Categories
      summary: Post Kategori Note
      description: |
        post data category
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: Post Category
        description: Category Note
        schema:
          type: object
          required:
          - name
          properties:
            name:
              type: string
              example: Puisi
      responses:
        200:
          description: Response Post Category
          schema:
            type: object
            properties:
              status_code:
                type: integer
                example: 200
              message:
                type: string
                example: 'OK'
              data:
                type : object
                $ref: '#/definitions/Categories'
        400:
          description: Bad Request
  /categories/{catID}:
    get:
      security:
          - bearerAuth: []
      tags:
      - Categories
      summary: Kategori Note By ID
      description: |
        get data category by id
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
        - in: path
          name: catID
          required: true
          type: integer
      responses:
        200:
          description: OK
          schema:
            type: object
            $ref: '#/definitions/Categories'     
    put:
      security:
        - bearerAuth: []
      tags:
      - Categories
      summary: Update Kategori Note By ID
      description: |
        put data category by id
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
        - in: path
          name: catID
          required: true
          type: integer
        - in: body
          name: Put Category
          description: Category Note Update
          schema:
            type: object
            required:
            - name
            properties:
              name:
                type: string
                example: Puisi Update
      responses:
        200:
          description: OK
          schema:
            type: object
            $ref: '#/definitions/Categories'     
    delete:
      security:
        - bearerAuth: []
      tags:
      - Categories
      summary: Delete Kategori Note By ID
      description: |
        delete data category
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
        - in: path
          name: catID
          required: true
          type: integer
      responses:
        200:
          description: OK
          schema:
            type: object
            $ref: '#/definitions/Categories'
  /note:
    get:
      security:
        - bearerAuth: []
      tags:
      - Note
      summary: Get List Data Note
      description: |
        get some data note
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        200:
          description: Response Get Note
          schema:
            type: object
            properties:
              status_code:
                type: integer
                example: 200
              message:
                type: string
                example: 'OK'
              data:
                type: array
                $ref: '#/definitions/Notes'
        400:
          description: Bad Request
    post:
      security:
          - bearerAuth: []
      tags:
      - Note
      summary: Post Note
      description: |
        post data Note
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: Post Note
        description: Note
        schema:
          type: object
          required:
          - user_id
          - category_id
          - title
          - note
          - is_free
          properties:
            user_id :
              type: integer
              example: 1
            category_id :
              type: integer
              example: 1
            title:
              type: string
              example: Puisi Aku
            note:
              type: string
              example: Aku adalah aku
            is_free:
              type: boolean
              example: true
      responses:
        200:
          description: Response Post Note
          schema:
            type: object
            properties:
              status_code:
                type: integer
                example: 200
              message:
                type: string
                example: 'OK'
              data:
                type: object
                $ref: '#/definitions/Notes'
        400:
          description: Bad Request
  /notes/{noteID}:
    get:
      security:
          - bearerAuth: []
      tags:
      - Note
      summary: Get Note By ID
      description: |
        get data Note by id
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
        - in: path
          name: noteID
          required: true
          type: integer
      responses:
        200:
          description: OK
          schema:
            type: object
            $ref: '#/definitions/Notes'     
    put:
      security:
        - bearerAuth: []
      tags:
      - Note
      summary: Update a Note by ID.
      description: |
        get data Note by id
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
        - in: path
          name: noteID
          required: true
          type: integer
        - in: body
          name: Put Note
          description: Note Update
          schema:
            type: object
            required:
            - user_id
            - category_id
            - title
            - note
            - is_free
            properties:
              user_id :
                type: integer
                example: 1
              category_id :
                type: integer
                example: 1
              title:
                type: string
                example: Puisi Aku
              note:
                type: string
                example: Aku adalah aku
              is_free:
                type: boolean
                example: true
      responses:
        200:
          description: OK
          schema:
            type: object
            $ref: '#/definitions/Notes'     
    delete:
      security:
        - bearerAuth: []
      tags:
      - Note
      summary: Delete a Note by ID.
      description: |
        get data Note by id
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
        - in: path
          name: noteID
          required: true
          type: integer
      responses:
        200:
          description: OK
          schema:
            type: object
            $ref: '#/definitions/Notes'
definitions:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  Login:
    type: object
    required:
    - email
    - password
    properties:
      email:
        type: string
        example: john.doe@gmail.com
      password:
        type: string
        example: QwanjjaseuQeq
        description: encrypted password AES
  Register:
    type: object
    required:
    - name
    - email
    - password
    - created_at
    - updated_at
    properties:
      name:
        type: string
        example: John Doe
      email:
        type: string
        example: john.doe@gmail.com
      password:
        type: string
        example: QwanjjaseuQeq
        description: encrypted password AES
      created_at:
        type: string
        example: 2021-08-09T12:02:57Z
        format: date-time
      updated_at:
        type: string
        example: 2021-08-09T12:02:57Z
        format: date-time
  Categories:
    type: object
    required:
    - name
    - created_at
    - updated_at
    properties:
      name:
        type: string
        example: Puisi
      created_at:
        type: string
        example: 2021-08-09T12:02:57Z
        format: date-time
      updated_at:
        type: string
        example: 2021-08-09T12:02:57Z
        format: date-time
  Notes:
    type: object
    required:
    - user_id
    - category_id
    - title
    - note
    - is_free
    - created_at
    - updated_at
    properties:
      user_id:
        type: integer
        example: 1
      category_id:
        type: integer
        example: 1
      title:
        type: string
        example: Aku
      note:
        type: string
        example: Aku adalah Aku
      is_free:
        type: boolean
        example: true
      created_at:
        type: string
        example: 2021-08-09T12:02:57Z
        format: date-time
      updated_at:
        type: string
        example: 2021-08-09T12:02:57Z
        format: date-time
  JWT:
    type: object
    required:
    - token
    - expire_token
    - refresh_token
    - expire_refresh_token
    properties:
      email:
        type: string
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.|eyJleHAiOjE2Mjg1MTA1NzcsImp0aSI6ImV5SmhiR2NpT2l a7C6ZcazsgjdKXR2eXOPRzBhRv99NOaDMNN2gyYDE2Y
      expire_token:
        type: string
        example: 2021-08-09T12:02:57Z
        format: date-time
      refresh_token:
        type: string
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.|eyJleHAiOjE2Mjg1MTA1NzcsImp0aSI6ImV5SmhiR2NpT2l a7C6ZcazsgjdKXR2eXOPRzBhRv99NOaDMNN2gyYDE2Y
      expire_refresh_token:
        type: string
        example: 2021-08-09T12:02:57Z
        format: date-time
security:
  - bearerAuth: []